language: cpp
os: linux
dist: focal
env:
  global:
    - MAKEFLAGS=-j2
  jobs:
    - LIBTORRENT_BRANCH=RC_1_1
    - LIBTORRENT_BRANCH=RC_1_2
    - LIBTORRENT_BRANCH=RC_2_0
addons:
  apt:
    packages:
      - libboost-all-dev
      - libfuse-dev
      - libcurl4-openssl-dev
before_script:
  - ./scripts/build-libtorrent $LIBTORRENT_BRANCH /usr
  - autoreconf -i
